add UCSC tool description
ncihtan/htan-portal pull request #593
Opened 2024-02-27 03:35 UTC by inodb

Partially fix https://github.com/ncihtan/htan-portal/issues/592

2024-02-27 03:47 UTC, onursumer requested changes
Looks like we are importing the wrong component for tool details

2024-02-27 03:47 UTC, onursumer commented on components/tool/toolDetails.tsx
> +import UCSCXena from './CytoCommunity';
```suggestion
import UCSCXena from './UCSCXena';
```

2024-02-27 03:47 UTC, onursumer commented on components/tool/UCSCXena.tsx
> +}
```suggestion
}

export default UCSCXena;
```

2024-02-28 08:52 UTC, jingchunzhu commented
Using the testing site, the Xena team notice these issues below

1. missing Xena Icon on "Atlas" tab
2. on "Files" tab, when there are linkouts to both "UCSC Xena" and "Minerva",  Minerva imaging thumbnail/linkout disappears
3. missing "UCSC Xena" under "ANALYSIS TOOLS" 

We identified three more HTAN files that can be linked out to Xena. If it is not too much trouble, can those these be added?

HTA7_926_1015  https://beta.xenabrowser.net/singlecell/?hub=https://previewsinglecell.xenahubs.net:443&defaultTable=htan&study=HTA7_926_8

HTA7_934_1016  https://beta.xenabrowser.net/singlecell/?hub=https://previewsinglecell.xenahubs.net:443&defaultTable=htan&study=HTA7_934_9

HTA7_16_1002     https://beta.xenabrowser.net/singlecell/?hub=https://previewsinglecell.xenahubs.net:443&defaultTable=htan&study=HTA7_16_2

2024-03-20 20:10 UTC, onursumer commented
@jingchunzhu Thanks for the feedback! We were able to fix the issues you pointed out. Can you do a final check? If everything looks good, we would like to make this available on the data portal.

2024-03-20 22:24 UTC, jingchunzhu commented
Looks great on the preview site. Thank you everyone.

2024-03-20 22:32 UTC, onursumer approved these changes

2024-03-21 14:46 UTC, merged